CREATE TABLE EM_EMAILKERTING (
 EMAILMARKETINGID INT NOT NULL,
 CreatedDate DATE WITH TIME ZONE,
 CreatedBy VARCHAR(10),
 STATUS VARCHAR(5) NOT NULL,
 TempID INT NOT NULL
);

ALTER TABLE EM_EMAILKERTING ADD CONSTRAINT PK_EM_EMAILKERTING PRIMARY KEY (EMAILMARKETINGID);


CREATE TABLE EM_EmailMarketingDetail (
 DetailID INT NOT NULL,
 CustomerID INT NOT NULL,
 EMAILMARKETINGID INT NOT NULL,
 Status VARCHAR(10) NOT NULL,
 EmailContent VARCHAR(10) NOT NULL
);

ALTER TABLE EM_EmailMarketingDetail ADD CONSTRAINT PK_EM_EmailMarketingDetail PRIMARY KEY (DetailID);


CREATE TABLE EM_Template (
 TempID INT NOT NULL,
 TempName VARCHAR(10) NOT NULL,
 TempContent VARCHAR(10) NOT NULL,
 CreatedDate DATE,
 EMAILMARKETINGID INT NOT NULL
);

ALTER TABLE EM_Template ADD CONSTRAINT PK_EM_Template PRIMARY KEY (TempID);


CREATE TABLE Entity3 (
);


ALTER TABLE EM_EMAILKERTING ADD CONSTRAINT FK_EM_EMAILKERTING_0 FOREIGN KEY (TempID) REFERENCES EM_Template (TempID);


ALTER TABLE EM_EmailMarketingDetail ADD CONSTRAINT FK_EM_EmailMarketingDetail_0 FOREIGN KEY (EMAILMARKETINGID) REFERENCES EM_EMAILKERTING (EMAILMARKETINGID);


ALTER TABLE EM_Template ADD CONSTRAINT FK_EM_Template_0 FOREIGN KEY (EMAILMARKETINGID) REFERENCES EM_EMAILKERTING (EMAILMARKETINGID);


